name: CI

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: KinD (Kubernetes in Docker) Action
        uses: engineerd/setup-kind@v0.1.0
      - name: Checkout
        uses: actions/checkout@master
      - name: Kube Test Action
        uses: saintube/Kube-Test@master
      
      - name: Get app deploer type
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl get deployment 
          kubectl get pod 
          kubectl get statefulset
          pwd
          ls $GITHUB_WORKSPACE/.kubetest/


    # - uses: engineerd/setup-kind@v0.1.0
    # - name: Testing
    #   run: |
    #     export KUBECONFIG="$(kind get kubeconfig-path)"
    #     echo $KUBECONFIG
    #     kubectl cluster-info
    #     kubectl get pods -n kube-system
    
    # - name: Run ansible-playbook
    #   run: |
    #     export KUBECONFIG="$(kind get kubeconfig-path)"
    #     echo $KUBECONFIG
    #     cd $GITHUB_WORKSPACE
    #     # sudo mkdir /ansible
    #     # sudo echo "[local]" >> /etc/ansible/hosts
    #     # sudo echo "127.0.0.1" >> /etc/ansible/hosts
    #     ansible-playbook -v test.yml
    
